package com.ngeso.security;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.BeforeClass;
import org.junit.Test;

import com.ngeso.security.exception.TokenExpiredException;
import com.ngeso.security.exception.TokenInvalidException;
import com.ngeso.security.model.Token;
import com.ngeso.security.token.TokenParser;

public class TokenParserTest {

	private static TokenParser tokenParser;
	private final String token_exp="eyJ4NXQjUzI1NiI6IkdJVWRYMDF1aVBOYklwSGNmTG9aQ3AxTmJvQ1RmS19nTUJmWHZjek56ejgiLCJ4NXQiOiJBZE1JVE81bTBrUGh6dEJHVU5WN01SdDgxODQiLCJraWQiOiJTSUdOSU5HX0tFWSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJkYWMxNmY2ZTI0MGM0YzRkYjJlNGU0ZjdiNzVkZjI0NyIsInVzZXIudGVuYW50Lm5hbWUiOiJpZGNzLWIwMmJjMWNjYTdjNjQ1OGFhYzY2MTZhZTM0MjQyMTQzIiwic3ViX21hcHBpbmdhdHRyIjoidXNlck5hbWUiLCJpc3MiOiJodHRwczpcL1wvaWRlbnRpdHkub3JhY2xlY2xvdWQuY29tXC8iLCJ0b2tfdHlwZSI6IkFUIiwiY2xpZW50X2lkIjoiZGFjMTZmNmUyNDBjNGM0ZGIyZTRlNGY3Yjc1ZGYyNDciLCJhdWQiOiJodHRwczpcL1wvMTMwLjE2Mi42OC42Mzo5MDIyIiwic3ViX3R5cGUiOiJjbGllbnQiLCJzY29wZSI6IkVEVCIsImNsaWVudF90ZW5hbnRuYW1lIjoiaWRjcy1iMDJiYzFjY2E3YzY0NThhYWM2NjE2YWUzNDI0MjE0MyIsImV4cCI6MTU0NDAxNDYwOCwiaWF0IjoxNTQ0MDE0MzA4LCJjbGllbnRfZ3VpZCI6ImFmYjY2ODZiYjI3NzRkZTZhYzllMWZlNTk5Y2I5YWUyIiwiY2xpZW50X25hbWUiOiJOR0VTTyIsInRlbmFudCI6ImlkY3MtYjAyYmMxY2NhN2M2NDU4YWFjNjYxNmFlMzQyNDIxNDMiLCJqdGkiOiI3ODIxYjUxMS1hM2ZhLTQ4Y2EtYTk1ZS00NWQxZWE5MGFjNjMifQ.DO7Qbh9COpy6NozIjcLtH1o5a6TvAIiS3w4Wv64o5DXcRN0Df-2-tnYqGiG3pqybLJBC00-RLCS6Ud-zf15BOfkkWBQipWyMQ2zOMLAY3AdyqZEJaVZ1eyQrF01VdjlwqhLSigdFb0anl8WJCUMiKXOLDwWKRDuvFVy9eJWp-qfyvaDGuLiciuCMAc8uLeSR-enGHfBBOkFo3A1UbT8gK-UE36hnsWZ9QdapMftOzO0BYZpJ2cN8T5eeYjoV1defQZpnSYvyHJ6WC5itk1vW12gFlF-z3UZz-MZrhTklLAswArd6v35SoWBCbqhK6KTAxE2iE0UnNqPRz5-KmjlGdg";
	private final String token_ok=
			"eyJ4NXQjUzI1NiI6IkdJVWRYMDF1aVBOYklwSGNmTG9aQ3AxTmJvQ1RmS19nTUJmWHZjek56ejgiLCJ4NXQiOiJBZE1JVE81bTBrUGh6dEJHVU5WN01SdDgxODQiLCJraWQiOiJTSUdOSU5HX0tFWSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJkYWMxNmY2ZTI0MGM0YzRkYjJlNGU0ZjdiNzVkZjI0NyIsInVzZXIudGVuYW50Lm5hbWUiOiJpZGNzLWIwMmJjMWNjYTdjNjQ1OGFhYzY2MTZhZTM0MjQyMTQzIiwic3ViX21hcHBpbmdhdHRyIjoidXNlck5hbWUiLCJpc3MiOiJodHRwczpcL1wvaWRlbnRpdHkub3JhY2xlY2xvdWQuY29tXC8iLCJ0b2tfdHlwZSI6IkFUIiwiY2xpZW50X2lkIjoiZGFjMTZmNmUyNDBjNGM0ZGIyZTRlNGY3Yjc1ZGYyNDciLCJhdWQiOiJodHRwczpcL1wvMTMwLjE2Mi42OC42Mzo5MDIyIiwic3ViX3R5cGUiOiJjbGllbnQiLCJzY29wZSI6IkVEVCIsImNsaWVudF90ZW5hbnRuYW1lIjoiaWRjcy1iMDJiYzFjY2E3YzY0NThhYWM2NjE2YWUzNDI0MjE0MyIsImV4cCI6MTU0NDAyMTMwMiwiaWF0IjoxNTQ0MDIxMDAyLCJjbGllbnRfZ3VpZCI6ImFmYjY2ODZiYjI3NzRkZTZhYzllMWZlNTk5Y2I5YWUyIiwiY2xpZW50X25hbWUiOiJOR0VTTyIsInRlbmFudCI6ImlkY3MtYjAyYmMxY2NhN2M2NDU4YWFjNjYxNmFlMzQyNDIxNDMiLCJqdGkiOiI0MWYyMTRiMS0wMTQ1LTQyYWItOGVkYy0yMzY3MmNmODg2OTEifQ.EThaoD3H9kK0e5T34ASCvIsuuzkcixpPqRlz4iDTqBieTIrpHbo3lDMHB0mlZmPYEEy9yTBaXg7JWtuXgGHfcKAsOMzEuGxi4bXwJoPfyKb2lMUYlg4FlKtDs9quy5KLWSoCmnNp1ctt15dsYd4MuQvmxTTSA-WImVLC23Xsi_4kbbSaxVlQqZQCT0pjffksagwjHNXObFxGLjA8UUNav06WEUXHQipZTcJfZfzUe36T9RCTkVQefLvj7pFmoHnbrx5ZvX9V6axZvRFuyHtHwIXf8LJJdQvPlGdSl2JAkyn92uOT8PDoCDYRFh1QRuFShNZHCf8QtZjvL53UW4dSqA";
	@BeforeClass
	public static void prepare() {
		tokenParser=new TokenParser();
	}

	@Test(expected=TokenInvalidException.class)
	public void TokenWrong() {
		tokenParser.verifyTokenAndExtractIdentity("abcd");
	}

	@Test(expected=TokenExpiredException.class)
	public void TokenExpired() {
		tokenParser.verifyTokenAndExtractIdentity(token_exp);
	}

	@Test
	public void TokenOK() {
		final Token theToken=tokenParser.verifyTokenAndExtractIdentity(token_ok);
		assertThat(theToken.getMpId()).isNotEmpty();
	}


}
