package com.ngeso.security;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.BeforeClass;
import org.junit.Test;

import com.ngeso.security.exception.TokenExpiredException;
import com.ngeso.security.exception.TokenInvalidException;
import com.ngeso.security.model.Token;
import com.ngeso.security.token.TokenParser;

public class TokenParserTest {

	private static TokenParser tokenParser;
	private final String token_exp="eyJ4NXQjUzI1NiI6Ikt3bF9oc0M0TEZnTEtLbG44UkNiRDdsVzhLeWtxMFRjV0t0RENoNW1XUzAiLCJ4NXQiOiIyZi1tSkxsUm5pTnpuOWVucG91eTdXck9iMUUiLCJraWQiOiJTSUdOSU5HX0tFWSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3Y2I3ODFmOWQwMTU0ZmM5OWUxNzQ1MzZkOTA2M2ZjOCIsInVzZXIudGVuYW50Lm5hbWUiOiJpZGNzLTRhNTU2YWRhZTVlNDRkY2ZhZTIzYTQ3M2M5YzVlMzNlIiwic3ViX21hcHBpbmdhdHRyIjoidXNlck5hbWUiLCJpc3MiOiJodHRwczpcL1wvaWRlbnRpdHkub3JhY2xlY2xvdWQuY29tXC8iLCJ0b2tfdHlwZSI6IkFUIiwiY2xpZW50X2lkIjoiN2NiNzgxZjlkMDE1NGZjOTllMTc0NTM2ZDkwNjNmYzgiLCJhdWQiOiJOR0VTTyIsInN1Yl90eXBlIjoiY2xpZW50Iiwic2NvcGUiOiJFRFQiLCJjbGllbnRfdGVuYW50bmFtZSI6ImlkY3MtNGE1NTZhZGFlNWU0NGRjZmFlMjNhNDczYzljNWUzM2UiLCJleHAiOjE1NDQ1NDk5OTYsImlhdCI6MTU0NDU0OTY5NiwiY2xpZW50X2d1aWQiOiJjNWIxYzhlYzA2ODY0MmJmOTg2M2ViZTQ0ZGIxYjAzOCIsImNsaWVudF9uYW1lIjoiUGFydGljaXBhbnRfMSIsInRlbmFudCI6ImlkY3MtNGE1NTZhZGFlNWU0NGRjZmFlMjNhNDczYzljNWUzM2UiLCJqdGkiOiJlM2VmNzJmMy0yOGMxLTQxZTItYWMxMi0yYTM1ZTRhNmQzMjcifQ.wXxvxzG2R_0yB3oJ-usiKmPFM6ZOgb7CM8qpgj8TgbAz7MXryFCYP3Js_vyxoDN5k2MwRGOJq1kyrab0J-pYH8XfroRezcCvrTzNAyBpBRPCg97uiArhlqM4ID00TxbB9V9dW8RdrLE12hjRpq5hI5LbbGDKz_fch5zBSBddr2ujGvcvrh8ZVCe-XIelmaW3VGCSC9evXapRdtaXgSP_HS6LsY4MjvGmsua-Thmq7s1SLzo582ZStowJ6x5X-ilvht7xV-TAZTSjY74zLqQWFmrzvUaElTTWWqtEpnc-8eD4ugdNzWfqbULjFzsf5UFCgFeI0YnUdHsMuvgeH7ielg";

	@BeforeClass
	public static void prepare() {
		tokenParser=new TokenParser();
	}

	@Test(expected=TokenInvalidException.class)
	public void TokenWrong() {
		tokenParser.verifyTokenAndExtractIdentity("abcd");
	}

	@Test(expected=TokenExpiredException.class)
	public void TokenExpired() {
		tokenParser.verifyTokenAndExtractIdentity(token_exp);
	}

	@Test
	public void TokenOK() {
		final Token theToken=tokenParser.verifyTokenAndExtractIdentity(BeanTests.getToken(Constants.scopeEDT));
		assertThat(theToken.getMpId()).isNotEmpty();
	}


}
